var databases =
    [
        { "rendering": "Trident", "browser": "Internet Explorer 4.0", "platform": "Win 95+", "version": "4", "grade": "X" },
        { "rendering": "Trident", "browser": "Internet Explorer 5.0", "platform": "Win 95+", "version": "5", "grade": "C" },
        { "rendering": "Trident", "browser": "Internet Explorer 5.5", "platform": "Win 95+", "version": "5.5", "grade": "A" },
        { "rendering": "Trident", "browser": "Internet Explorer 6", "platform": "Win 98+", "version": "6", "grade": "A" },
        { "rendering": "Trident", "browser": "Internet Explorer 7", "platform": "Win XP SP2+", "version": "7", "grade": "A" },
        { "rendering": "Trident", "browser": "AOL browser (AOL desktop)", "platform": "Win XP", "version": "6", "grade": "A" },
        { "rendering": "Gecko", "browser": "Firefox 1.0", "platform": "Win 98+ / OSX.2+", "version": "1.7", "grade": "A" },
        { "rendering": "Gecko", "browser": "Firefox 1.5", "platform": "Win 98+ / OSX.2+", "version": "1.8", "grade": "A" },
        { "rendering": "Gecko", "browser": "Firefox 2.0", "platform": "Win 98+ / OSX.2+", "version": "1.8", "grade": "A" },
        { "rendering": "Gecko", "browser": "Firefox 3.0", "platform": "Win 2k+ / OSX.3+", "version": "1.9", "grade": "A" },
        { "rendering": "Gecko", "browser": "Camino 1.0", "platform": "OSX.2+", "version": "1.8", "grade": "A" },
        { "rendering": "Gecko", "browser": "Camino 1.5", "platform": "OSX.3+", "version": "1.8", "grade": "A" },
        { "rendering": "Gecko", "browser": "Netscape 7.2", "platform": "Win 95+ / Mac OS 8.6-9.2", "version": "1.7", "grade": "A" },
        { "rendering": "Gecko", "browser": "Netscape Browser 8", "platform": "Win 98SE+", "version": "1.7", "grade": "A" },
        { "rendering": "Gecko", "browser": "Netscape Navigator 9", "platform": "Win 98+ / OSX.2+", "version": "1.8", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.0", "platform": "Win 98+ / OSX.1+", "version": "1", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.1", "platform": "Win 98+ / OSX.1+", "version": "1.1", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.2", "platform": "Win 98+ / OSX.1+", "version": "1.2", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.3", "platform": "Win 98+ / OSX.1+", "version": "1.3", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.4", "platform": "Win 98+ / OSX.1+", "version": "1.4", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.5", "platform": "Win 98+ / OSX.1+", "version": "1.5", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.6", "platform": "Win 98+ / OSX.1+", "version": "1.6", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.7", "platform": "Win 98+ / OSX.1+", "version": "1.7", "grade": "A" },
        { "rendering": "Gecko", "browser": "Mozilla 1.8", "platform": "Win 98+ / OSX.1+", "version": "1.8", "grade": "A" },
        { "rendering": "Gecko", "browser": "Seamonkey 1.1", "platform": "Win 98+ / OSX.2+", "version": "1.8", "grade": "A" },
        { "rendering": "Gecko", "browser": "Epiphany 2.20", "platform": "Gnome", "version": "1.8", "grade": "A" },
        { "rendering": "KHTML", "browser": "Konqureror 3.1", "platform": "KDE 3.1", "version": "3.1", "grade": "C" },
        { "rendering": "KHTML", "browser": "Konqureror 3.3", "platform": "KDE 3.3", "version": "3.3", "grade": "A" },
        { "rendering": "KHTML", "browser": "Konqureror 3.5", "platform": "KDE 3.5", "version": "3.5", "grade": "A" },
        { "rendering": "Misc", "browser": "NetFront 3.1", "platform": "Embedded devices", "version": "-", "grade": "C" },
        { "rendering": "Misc", "browser": "NetFront 3.4", "platform": "Embedded devices", "version": "-", "grade": "A" },
        { "rendering": "Misc", "browser": "Dillo 0.8", "platform": "Embedded devices", "version": "-", "grade": "X" },
        { "rendering": "Misc", "browser": "Links", "platform": "Text only", "version": "-", "grade": "X" },
        { "rendering": "Misc", "browser": "Lynx", "platform": "Text only", "version": "-", "grade": "X" },
        { "rendering": "Misc", "browser": "IE Mobile", "platform": "Windows Mobile 6", "version": "-", "grade": "C" },
        { "rendering": "Misc", "browser": "PSP browser", "platform": "PSP", "version": "-", "grade": "C" },
        { "rendering": "Other browsers", "browser": "All others", "platform": "-", "version": "-", "grade": "U" },
        { "rendering": "Presto", "browser": "Opera 7.0", "platform": "Win 95+ / OSX.1+", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Opera 7.5", "platform": "Win 95+ / OSX.2+", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Opera 8.0", "platform": "Win 95+ / OSX.2+", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Opera 8.5", "platform": "Win 95+ / OSX.2+", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Opera 9.0", "platform": "Win 95+ / OSX.3+", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Opera 9.2", "platform": "Win 95+ / OSX.3+", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Opera 9.5", "platform": "Win 95+ / OSX.3+", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Opera for Wii", "platform": "Wii", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Nokia N800", "platform": "N800", "version": "-", "grade": "A" },
        { "rendering": "Presto", "browser": "Nintendo DS browser", "platform": "Nintendo DS", "version": "8.5", "grade": "C/A1" },
        { "rendering": "Webkit", "browser": "Safari 1.2", "platform": "OSX.3", "version": "125.5", "grade": "A" },
        { "rendering": "Webkit", "browser": "Safari 1.3", "platform": "OSX.3", "version": "125.5", "grade": "A" },
        { "rendering": "Webkit", "browser": "Safari 2.0", "platform": "OSX.4+", "version": "419.3", "grade": "A" },
        { "rendering": "Webkit", "browser": "Safari 3.0", "platform": "OSX.4+", "version": "522.1", "grade": "A" },
        { "rendering": "Webkit", "browser": "OmniWeb 5.5", "platform": "OSX.4+", "version": "420", "grade": "A" },

    ]